name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Deploy
      run: |
        # Add IP to known hosts
        ssh-keyscan -H 192.168.68.66 >> ~/.ssh/known_hosts
        
        # Run deployment commands
        ssh -o StrictHostKeyChecking=no pi@192.168.68.66 "
          cd ~/compendium
          git pull
          npm install
          systemctl --user restart compendium
        "