name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Install mDNS tools
      run: |
        sudo apt-get update
        sudo apt-get install -y avahi-utils
        
    - name: Deploy
      run: |
        # Resolve mDNS hostname
        echo "Resolving compendium.local..."
        PI_IP=$(avahi-resolve-host-name compendium.local | awk '{print $2}')
        
        if [ -z "$PI_IP" ]; then
          echo "Failed to resolve compendium.local - using fallback IP"
          PI_IP="192.168.68.66"
        fi
        
        echo "Using IP: $PI_IP"
        
        # Add IP to known hosts
        ssh-keyscan -H $PI_IP >> ~/.ssh/known_hosts
        
        # Run deployment commands
        echo "Running deployment commands..."
        ssh -o StrictHostKeyChecking=no pi@$PI_IP "
          cd ~/compendium
          git pull
          npm install
          systemctl --user restart compendium
        "
