name: Create Deployment Package

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    # Configure .env file for key-based authentication and secure connections
    - name: Configure .env file for secure deployment
      run: |
        # Remove any TOKEN_SECRET entries to enforce key-based authentication
        sed -i '/^TOKEN_SECRET=/d' .env || true
        
        # Configure WebSocket connection settings
        echo "VPS_PATH=/relay" >> .env
        echo "VPS_PING_INTERVAL=25000" >> .env
        echo "VPS_CONNECTION_TIMEOUT=30000" >> .env
        
        # In production, force WSS by setting port to 443
        echo "VPS_WS_PORT=443" >> .env
        
        # Show what's in the .env file
        echo "Updated .env file with these variables:"
        cat .env | cut -d= -f1
    
    # Create deployment package
    - name: Create deployment package
      run: |
        # Create version file with timestamp and commit hash
        echo "$(date -u +'%Y-%m-%d %H:%M:%S UTC') - $(git rev-parse --short HEAD)" > VERSION
        
        # Create deployment package
        mkdir -p deployment
        tar -czf deployment/compendium-deploy.tar.gz --exclude=node_modules --exclude=.git --exclude=deployment .
        
        # Create a simple version info file
        echo "$(date -u +'%Y%m%d%H%M%S')-$(git rev-parse --short HEAD)" > deployment/version.txt
    
    # Upload the artifact using GitHub's built-in artifact storage
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: compendium-deploy
        path: deployment/compendium-deploy.tar.gz
