name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Add SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: |
          ${{ secrets.SSH_PRIVATE_KEY }}
      
    - name: Deploy
      run: |
        # Debug info
        echo "Using PI_IP: ${{ secrets.PI_IP }}"
        
        # Add IP to known hosts
        ssh-keyscan -H ${{ secrets.PI_IP }} >> ~/.ssh/known_hosts
        
        # Test connection first
        echo "Testing SSH connection..."
        ssh -o StrictHostKeyChecking=no -v pi@${{ secrets.PI_IP }} "echo Connection successful"
        
        # Run deployment commands
        echo "Running deployment commands..."
        ssh -o StrictHostKeyChecking=no pi@${{ secrets.PI_IP }} "
          cd ~/compendium
          git pull
          npm install
          systemctl --user restart compendium
        "